# Generated by Django 5.1.4 on 2024-12-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("img_path", models.CharField(max_length=255)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("genre", models.JSONField(help_text="List of genres")),
                ("language", models.CharField(max_length=100)),
                ("mpaa_type", models.CharField(max_length=10)),
                ("mpaa_label", models.CharField(max_length=255)),
                ("user_rating", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
