# Generated by Django 5.1.4 on 2024-12-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="Mpaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mpaa_type", models.CharField(max_length=10)),
                ("mpaa_label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "mpaa",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="mpaa_label",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="mpaa_type",
        ),
        migrations.AddField(
            model_name="movie",
            name="mpaa_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="movie",
            table="movie",
        ),
    ]
