# Generated by Django 5.1.4 on 2024-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0003_alter_mpaa_mpaa_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mpaa",
            name="mpaa_type",
            field=models.CharField(max_length=10),
        ),
    ]
